version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      tags:
        - shirohara/avatar:frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      tags:
        - shirohara/avatar:backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/AvatarDB?ssl=false

volumes:
  mongo-data:
